### ISSUE TITLE
Changing map in Brickadia crashes Brikkit

### ISSUE THREAD

**Issue by n42k** [n42k/brikkit#3]
```
events.js:116
    handler.call(self, arg1);
            ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
    at StateMachineJoin.parseLine (/snapshot/brikkit/sm_join.js:0:0)
    at Brikkit._stateMachineJoinHandleLine (/snapshot/brikkit/brikkit.js:0:0)
    at Brikkit._handleBrickadiaLine (/snapshot/brikkit/brikkit.js:0:0)
    at constructor._brickadia.on.line (/snapshot/brikkit/brikkit.js:0:0)
    at Interface.constructor.outRl.on.line (/snapshot/brikkit/brickadia.js:0:0)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
    at Socket.ondata (readline.js:139:10)
```

**Comment by n42k** [comment]
Closed by b022178de645464fdd14e82f2fe339d34eea6f4d.
