### ISSUE TITLE
Brickadia closing not detected

### ISSUE THREAD

**Issue by n42k** [n42k/brikkit#4]
If Brickadia itself closes (and I assume, crashes), Brikkit is not aware of this fact until a plugin tries interacting with Brickadia. After this is done, the following error is thrown:

```
Error: This socket is closed
    at Socket._writeGeneric (net.js:733:18)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at Brickadia.write (/snapshot/brikkit/brickadia.js:0:0)
    at Brikkit.saveBricks (/snapshot/brikkit/brikkit.js:0:0)
    at Timeout.autosave [as _onTimeout] (/tmp/tmp-29030tcl5f4csLGNX/index.js:23:20)
    at ontimeout (timers.js:498:11)
```

**Comment by n42k** [comment]
Closed by f0b2623f99ac049206fd2feaab6eb4a8695c53d8.
